import pluralize from 'pluralize';
import { Scope, StructureKind, VariableDeclarationKind } from 'ts-morph';
import type { Behavior } from './config';
import { createProject } from './project';
import type { ModelNames } from './types';

/**
 * Header prepended to every scaffold.
 *
 * It must stay byte-stable across runs: the content hash recorded in the
 * manifest is what tells a later run whether the user has edited the file, so
 * anything varying (a timestamp, a version number) would make every run report
 * spurious changes.
 */
const HEADER = [
  '// Custom model scaffold generated by prisma-custom-models-generator.',
  '//',
  '// This file is yours to edit. Later `prisma generate` runs detect your',
  '// changes and leave the file alone; the generator only rewrites scaffolds it',
  '// created that are still untouched. Delete the file to get a fresh scaffold.',
  '',
  '',
].join('\n');

export function modelNames(modelName: string): ModelNames {
  const singularPascalCase =
    modelName.slice(0, 1).toUpperCase() + modelName.slice(1);
  const singularCamelCase =
    modelName.slice(0, 1).toLowerCase() + modelName.slice(1);
  // `DMMF.ModelMapping.plural` is declared as `string` but is undefined at
  // runtime on Prisma 7, so pluralisation stays local.
  const plural = pluralize(modelName.toLowerCase());
  const pluralPascalCase = plural.slice(0, 1).toUpperCase() + plural.slice(1);
  return { pluralPascalCase, singularCamelCase, singularPascalCase };
}

export function fileNameFor(modelName: string): string {
  return `${modelNames(modelName).pluralPascalCase}.ts`;
}

/**
 * Find models whose scaffolds would land on the same file.
 *
 * File names come from pluralising the model name, so a schema containing both
 * `Setting` and `Settings` (or `User` and `Users`, `Person` and `People`) maps
 * two models onto one path. Previous versions wrote both and kept whichever
 * came last, so one model silently got no scaffold at all.
 *
 * Comparison is case-insensitive because macOS and Windows file systems are:
 * `Data.ts` and `data.ts` are two paths on Linux and one everywhere else.
 *
 * Returns one entry per colliding file name, listing the models involved.
 */
export function findFileNameCollisions(
  modelNamesList: readonly string[],
): { fileName: string; models: string[] }[] {
  const byFileName = new Map<string, { fileName: string; models: string[] }>();

  for (const modelName of modelNamesList) {
    const fileName = fileNameFor(modelName);
    const key = fileName.toLowerCase();
    const existing = byFileName.get(key);
    if (existing) {
      existing.models.push(modelName);
    } else {
      byFileName.set(key, { fileName, models: [modelName] });
    }
  }

  return [...byFileName.values()].filter((entry) => entry.models.length > 1);
}

export type EmitInput = {
  modelName: string;
  behavior: Behavior;
  /** Module specifier the scaffold should import the client from. */
  clientImport: string;
};

/**
 * Render one scaffold to text. Pure: no disk access, no ambient state.
 */
export function emitModelFile({
  modelName,
  behavior,
  clientImport,
}: EmitInput): string {
  const { pluralPascalCase, singularCamelCase, singularPascalCase } =
    modelNames(modelName);

  const project = createProject();
  const sourceFile = project.createSourceFile(
    `/virtual/${pluralPascalCase}.ts`,
    undefined,
    { overwrite: true },
  );

  if (behavior === 'WRAP') {
    sourceFile.addImportDeclaration({
      moduleSpecifier: clientImport,
      namedImports: ['PrismaClient'],
      isTypeOnly: true,
    });
    sourceFile.addClass({
      name: pluralPascalCase,
      isExported: true,
      docs: [
        `Custom methods for the \`${singularPascalCase}\` model.\n\nInstantiate it with the delegate: \`new ${pluralPascalCase}(prisma.${singularCamelCase})\`.`,
      ],
      ctors: [
        {
          kind: StructureKind.Constructor,
          parameters: [
            {
              name: `prisma${singularPascalCase}`,
              type: `PrismaClient['${singularCamelCase}']`,
              isReadonly: true,
              scope: Scope.Private,
            },
          ],
        },
      ],
    });
  } else if (behavior === 'EXTEND') {
    sourceFile.addImportDeclaration({
      moduleSpecifier: clientImport,
      namedImports: ['PrismaClient'],
      isTypeOnly: true,
    });
    sourceFile.addFunction({
      name: pluralPascalCase,
      isExported: true,
      docs: [
        `Custom methods for the \`${singularPascalCase}\` model.\n\nWrap the delegate: \`const ${singularCamelCase}s = ${pluralPascalCase}(prisma.${singularCamelCase})\`.`,
      ],
      parameters: [
        {
          name: `prisma${singularPascalCase}`,
          type: `PrismaClient['${singularCamelCase}']`,
        },
      ],
      statements: [
        `return Object.assign(prisma${singularPascalCase}, {`,
        `  // define methods here, comma-separated`,
        `});`,
      ],
    });
  } else {
    sourceFile.addImportDeclaration({
      moduleSpecifier: clientImport,
      namedImports: ['Prisma'],
    });
    sourceFile.addVariableStatement({
      isExported: true,
      declarationKind: VariableDeclarationKind.Const,
      docs: [
        [
          `Custom methods for the \`${singularPascalCase}\` model, as a Prisma Client extension.`,
          ``,
          `Apply it with \`const prisma = base.$extends(${pluralPascalCase}Extension)\`,`,
          `then call \`prisma.${singularCamelCase}.yourMethod()\`.`,
          ``,
          `Example method:`,
          ``,
          `    async findByEmail(email: string) {`,
          `      const ctx = Prisma.getExtensionContext(this);`,
          `      return (ctx as any).findFirst({ where: { email } });`,
          `    },`,
        ].join('\n'),
      ],
      declarations: [
        {
          name: `${pluralPascalCase}Extension`,
          initializer: [
            `Prisma.defineExtension({`,
            `  name: '${pluralPascalCase}',`,
            `  model: {`,
            `    ${singularCamelCase}: {`,
            `      // define methods here, comma-separated`,
            `    },`,
            `  },`,
            `})`,
          ].join('\n'),
        },
      ],
    });
  }

  sourceFile.formatText({ indentSize: 2 });

  // Normalise line endings so a manifest written on one OS still matches on
  // another; otherwise every file would look edited after a checkout.
  const body = sourceFile.getFullText().replace(/\r\n/g, '\n');
  return `${HEADER}${body}`;
}
